### ISSUE TITLE
Feature request: Provide "raw" substitution data

### ISSUE THREAD

**Issue by xandhen** [darrencauthon/csharp-sparkpost#112]
Hi,

Internally in our project we have decoupled the sending and generation of emails for various reasons. This seems to cause us a bit of a headache when we want to use templates for the transmission with the current API though. From what I can find the Transmission class only lets us provide substitution data in a dictionary form. Since we are passing data between different parts of our system, our data is already encoded in a JSON string which is ready for the Sparkpost API. To decode this JSON string, only to have the Transmission class encode it again later on is a huge and unneccesary performance penalty.

Is there any possibility to add an alternative way to provide the substitution data to the Transmission class? Perhaps along the lines of a "raw" property on the Transmission class for providing a string JSON representation that would be selected before the substitution data dictionary. This logic could reside in the DataMapper class where the substitution data is assigned.

`public virtual IDictionary<string, object> ToDictionary(Transmission transmission)
{
}`

I'm not sure how to get the final JSON serialization to treat the JSON object as a "raw data" though so it doesn't get embedded in "" during serialization.

**Comment by darrencauthon** [comment]
Hmmm..... let me think about this for just a bit.

I think I need to have it be a dictionary, just to aid other users.  SparkPost expects, essentially, a plain ol' JSON document.  I made it a dictionary because I thought that would be the easiest way for users to quickly toss in some data into the template, like:

```c#
.Data["first_name"] = "Darren";
```

But given how the DataMapper works, the data properly could technically take any object and rely on the mapper to do the conversion.  So one could, possibly, do this:

```c#
.Data = new { FirstName = "Darren" };
```

So maybe we don't need to necessarily use a dictionary.  I'll chew on this.

But you are asking if you could set your own string.  Well, if I broke out Data as an object reference then you could, as a string would just be sent over raw.

Hmm.... I'm going to have to think on this one for a bit.

**Comment by darrencauthon** [comment]
@xandhen But in the meantime, here is my next target to help you:

https://github.com/darrencauthon/csharp-sparkpost/blob/2f96ade177715bb591c80a25a83b091c50ae92c6/src/SparkPost/Client.cs#L32

It's this one line that is the real problem

```c#
var dataMapper = new DataMapper(Version);
```

It's in the constructor, and there's no way to override it.  I could allow a custom data mapper to be inserted through custom settings.  Then you could override the default ```DataMapper``` with one that passes the data over however you wish.  You could could also inherit from ```Transmission``` to add this raw data property you want, making this raw string available to your own data mapper.

**Comment by darrencauthon** [comment]
- [ ] Add this to the projects board.
- [ ] Consider changing the dependencies on the DataMapper to lazy-loading functions, which will allow the DataMapper to be changes after the Client has been instantiated.
- [ ] Chew more on the idea of making substitution data a raw object.

**Comment by xandhen** [comment]
Thanks of the speedy response.

I understand the rationale behind the dictionary, it makes it very convenient to add smaller pieces of data rapidly. Having the dictionary also makes it easy to add the data incrementally rather than using anonymous object for most users. As you point out, serializing any object will however yield the same result JSON wise as an object is essentially a property-name/value dictionary.
Thats why I suggested a parallel "raw" property that could be set instead of the Dictionary.

Technically I guess you could add an optional parameter for the DataMapper to the Client constructor allowing one to override it there already. Otherwise the lazy loading will have to be implemented in the whole chain as it is shared from within the constructor.

I'm still figuring out how to control the serialization of a raw data property though. Since the Transmission as a class is basically being wrapped in a dictionary in the data mapper which is later serialized using JSON.net. Putting a raw JSON string into the dictionary will result in my JSON object string being wrapped in "" such as {"substitution_data":"my_raw_json_object"}. Probably this can be avoided by providing the raw data as a JRaw object instance rather than a string object instance.

**Comment by darrencauthon** [comment]
> Technically I guess you could add an optional parameter for the DataMapper to the Client constructor allowing one to override it there already. Otherwise the lazy loading will have to be implemented in the whole chain as it is shared from within the constructor.

I could bring it in as an optional parameter, but... I'd like to avoid any library-specific objects in the construction of the client.  I think it's just a personal thing, but just sticking with SparkPost configuration strings has caused the constructor to go a little crazy.  I have a custom settings object which I use to set optional variables, so I think I'll thread the ability to pass along a custom data mapper through that.  

I wrote most of this library in C# but, I think in Ruby.  I hate the second "raw" property not because it's a bad idea (because it's not) - this is just one of the messes we get into with static typing.  I also don't like the idea of having two properties that target a single output... should I put exceptions if both are set?  It's just a bit messy. 

I'm still chewing on this idea, but I think I'm going to go the route of exposing the data mapper.  Or gosh, maybe all of the components that are instantiated by this code.  Maybe I'll use a local copy of BoDi? :smile: I'll update this issue as I progress.

**Comment by asherber** [comment]
@xandhen I'm curious -- can you say a little more about why turning the JSON into a dictionary and then having it re-encoded during sending is a "huge" performance penalty? I may be missing something, but I ran some quick tests using 
```csharp
JsonConvert.DeserializeObject<Dictionary<string, object>>(json);
```
I created a list of 1000 JSON strings, each one containing 20 properties where the name and value were each a new GUID. Iterating through this list and deserializing each string into a dictionary took a total of less than 30ms.

**Comment by black-orchid** [comment]
I'm also interested in passing my own SubstitutionData json string; I'm would like to just call JsonConvert.SerializeObject() and pass that string directly to SparkPost, saving myself the step of deserializing it back into a dictionary.

**Comment by darrencauthon** [comment]
I'm going to go ahead and close this. It's not going to happen. 

I understand that it would be neat to be able to do this, but in the interest of all users of the library I think it is best to keep it a dictionary. 

If I can expose the mapper, it can be overwritten to hook to whatever one may wish. But I'm not going to embed a work-around into the core API just because a few C# devs don't want to use a dictionary.
