### ISSUE TITLE
Enclose Name in double quotes

### ISSUE THREAD

**Issue by osya** [darrencauthon/csharp-sparkpost#114]
Name value from transmission.Content.From.Name enclosed in double quotes in the "From" field in the email. It should not be enclosed in double quotes, or should be possibility to switch off these double quotes.

Here is my transmission.Content.From settings:
transmission.Content.From.Name = "Redfoodie";
transmission.Content.From.Email = "restaurants@sparkpostbox.com";

What is appears in email: "From: "Redfoodie" <restaurants@sparkpostbox.com>"
What I expect: "From: Redfoodie <restaurants@sparkpostbox.com>"

**Comment by darrencauthon** [comment]
Is this library responsible for this?

**Comment by darrencauthon** [comment]
What do you mean, "What I suspect" ?

**Comment by osya** [comment]
"expect". Sorry

**Comment by darrencauthon** [comment]
@osya I don't think it does.  I'll take a look later, but I don't remember writing any special logic to quotes appear.  

If you want to know if it's possible to disable quotes, I'd check the API.  This library closely mirrors the API, and if such a field appears we'll add it to the library.

I'm going to close this issue because I'm 99% sure that this is a matter for SparkPost.  You'll have to make this change request to them directly.

**Comment by osya** [comment]
@darrencauthon I agree with - it is not csharp-sparkpost, but Sparkpost API issue. This is the request for sending email: 

POST https://api.sparkpost.com/api/v1/transmissions HTTP/1.1
Authorization: 600038c91faa25207a948b476da10ccf88dbab64
Content-Type: application/json; charset=utf-8
Host: api.sparkpost.com
Content-Length: 7592
Expect: 100-continue
Connection: Keep-Alive

{"recipients":[{"address":{"email":"zurocojipi@maileme101.com"}}],"content":{"html":"...","subject":"Redfoodie Password Reset",**"from":{"name":"Redfoodie","email":"restaurants@sparkpostbox.com"**}},"total_recipients":0,"num_generated":0,"num_failed_generation":0,"num_invalid_recipients":0}

**Comment by osya** [comment]
I checked in PostMan that API https://api.sparkpost.com/api/v1/transmissions allows to use string for "from" attribute
```json
{
  "campaign_id": "postman_inline_both_example",
  "recipients": [
    {
      "address": "zurocojipi@maileme101.com"
    }
  ],
  "content": {
    "from": "Redfoodie <restaurants@sparkpostbox.com>",
    "subject": "SparkPost inline template example",
    "html": "<html><body>Here is your inline html, {{first_name or 'you great person'}}!<br></body></html>"
  }
}
```
It solves my problem. But csharp-sparkpost does not allow to use string for Transmission.Content.From property, as it has Address type. Could you please make possible to use strings for Transmission.Content.From field?

**Comment by darrencauthon** [comment]
Thinking.... I can't make it possible to use strings, as I don't want the code to have exception cases or multiple ways to do the same thing.  This is part of the pain we feel with static typing... the fact that we can't just have the property take BOTH cases.  I miss Ruby.

I think I have another alternative, though.  If someone creates a recipient, but they only set the email address, then I might be able to only return the string version of the email address.

**Comment by osya** [comment]
As I understand returning only the string version of the email address is not solving my issue. May be you should use `dynamic` type for `From` property? Or if you want to stay with static typing, may be you should create two `From` properties - private and public (surely the name of private property should be slightly different, _From, for example). And will be public properties `Name` and `Email`. User will initialize public property From, or public properties Name and Email. Then should be some method which will initialize private `From` property based on values of these three properties.

**Comment by darrencauthon** [comment]
I have to stay with static typing -- this library is for C#.  

The switch with a ```From``` property versus a ```Name``` and ```Email``` properties is exactly the type of thing I want to avoid... I think that's confusing to end users.  And it's against the flow of the entire library.  The objects this library use directly map to the SparkPost API, which means that I don't have much left-to-right type of programming (if any at all?).

I think the fix for this is to allow the mapper to be overwritten, which was requested for another ticket.  Then someone could override how the request is built before getting sent to SparkPost.

**Comment by osya** [comment]
"allow the mapper to be overwritten" - Ok. It will solve this issue. In such case this issue can be closed, I suppose. How you are going implement this? Using delegates? Or may be by create Factory for `Transmission` class, and this Factory will instantiate descendants of `Transmission` class with certain type for `From` property?
