### ISSUE TITLE
Is Metrics API supported?

### ISSUE THREAD

**Issue by jasneo** [darrencauthon/csharp-sparkpost#115]
I don't see any references to Metrics API. I am checking whether it's supported in this project.

Thanks

**Comment by asherber** [comment]
I'm working on an approach to this. Will be happy to contribute back to the project when it's complete.

**Comment by asherber** [comment]
@darrencauthon, I have a working implementation of Metrics, but I'd like to check with you on a couple of design decisions. What's the best way to proceed?

**Comment by darrencauthon** [comment]
Hey I'm sorry, busy weekend... haven't had a chance to sit and code. I'll get the other PR merged and deployed soon. Let's chat, what design do you want to talk over?
Get Outlook for iOS




On Sun, Nov 27, 2016 at 5:19 PM -0600, "asherber" <notifications@github.com> wrote:












@darrencauthon, I have a working implementation of Metrics, but I'd like to check with you on a couple of design decisions. What's the best way to proceed?

**Comment by asherber** [comment]
I just wanted to check the design with you so that I could make any needed changes while finishing up. I modeled most of it on what you've got with `MessageEvents`.

The four API functions that retrieve lists of resources (IP pools, sending IPs, domains, campaigns) are pretty straightforward. There's a query object you can fill out (like `MessageEventsQuery`) with the 5 optional parameters, and then you call `client.Metrics.GetDomains()` (or `GetCampaigns()`, etc.). What you get back is a `Response` object that has a `Results` property which is `IList<string>`.

The other functions are a little more complicated and require some knowledge of the API on the part of the user. There's a longer query object to populate; this object is used across all the functions, so it's up to the user to know which parameters are valid for which functions (most are valid for all functions, but for example, specifying `Precision` is only valid for deliverability by time series). The list of fields that the user wants returned from the call are specified using an enum-like class, so that the user doesn't have to know magic strings.

The calls themselves look like `client.Metrics.GetDeliverability()`, `GetDeliverabilityByDomain()`, etc. They return a `Response` object with a `Results` property that is a `IList<IDictionary<MetricsField, object>>`, basically turning the array of returned JSON results groups into a list of dictionaries. The dictionaries are keyed by the same enum-like type to avoid magic strings. Again, the user needs some knowledge of what returned fields to expect in order to work with the results. (The SparkPost Java library does things this way, but without the enum.) 

A couple of things I'm not sure about:

* The enums for requested fields (in the query object) and returned fields are different types, even though the latter duplicates all the values of the former (and then adds more). This was to keep users from requesting fields in the query that aren't valid in requests. For example, when you call `GetDeliverabilityByDomain()`, you get the `domain` field for free in the result without asking for it. Since we're already counting on some API knowledge on the user's part, I wonder if I shouldn't just make this all one type, for easier maintenance.
* Are the result sets sufficiently useful as they are? Tailoring the `Results` property to the specific function calls would be a lot of work. Even changing the property from a list of dictionaries to a dictionary of dictionaries (with the top-level dictionary keyed by the appropriate item, e.g., `domain` for `GetByDomain()`) is complicated. Again, the official Java library does things like I do, but I don't know if there have been complaints about that.

I'd appreciate any thoughts or comments on the above. The current state of this (working, but needs more testing and a little polish) is in https://github.com/asherber/csharp-sparkpost/tree/metrics

**Comment by darrencauthon** [comment]
Just based on what you've said, and without looking in-depth at the code... It doesn't make sense to me to use a dictionary while trying to avoid "magic strings."  I'll look at what you have deeper, but I should tell you:  I'm not a fan of enums, at least in the places this library has used them.  I accepted a pull request or two with them, and I regretted it later.  And I don't regret it out of some theoretical stance... the types can get in the way.

I'll have to learn more about the API and look over this branch, but sentences like this make me believe that the simplest solution is to just stick with strings:

> The enums for requested fields (in the query object) and returned fields are different types, even though the latter duplicates all the values of the former (and then adds more).

Strings are simple. :smile:

**Comment by darrencauthon** [comment]
Thank you for your work!  I will work to get it included in the main branch as soon as possible, once you say it's fully ready (like the other PR).

**Comment by asherber** [comment]
Happy to discuss strings vs. enums with you further. As you'll see, these aren't technically enums -- they're a class with `static readonly` fields that are convertible to strings. The idea is for the user to be able to do something like:
```csharp
string domain = dict[MetricsField.Domain];
```
rather than
```csharp
string domain = dict["domain"];
```
and having to make sure they spelled 'domain' correctly, every time they use it. Using a type lets the user have IntelliSense for discoverability and compile-time checking.

OTOH, if I play with conversion operators, I think I can get the dictionary keyed by string but still give the user the choice of using the enum to access it, if they want.

**Comment by darrencauthon** [comment]
Yeah, they make sense to me.  I did do a Control+F on your code and didn't see "enum" appear, but I just figured you hadn't push them or I was missing something... so I said "take a deeper look later."

I'm fine with that approach.  It allows the data to be what it is, without being forced to convert from strings to enums, and enums to strings.  It really helps when/if the API changes.  If it's a string, we don't have to change it.  If it's an enum, the library is broken. :frowning:

Thank you!

**Comment by asherber** [comment]
Okay, I changed this to using strings as the dictionary keys. `MetricsField` is now just a collection of consts for convenience and lets users forget about magic strings if they want:
```csharp
public static class MetricsField
{
  public const string Injected = "count_injected";
  // etc.
}
```
`dict[MetricsField.Injected]` still works, but so does `dict["count_injected"]`.

**Comment by asherber** [comment]
@darrencauthon I'm curious as to why you made the argument to `MessageEvents.List()` an `object` rather than a `MessageEventsQuery`. Is there a use case in which someone would pass in a different object? I followed your lead in `Metrics`, but frankly it would be useful to have a typed object in the calls so that I can check for required fields.

**Comment by darrencauthon** [comment]
@asherber I allow it to accept an object instead of a typed object so it will accept anonymous types.

For example, I could search for events like this:

```c#
client.MessageEvents.Find(new MessageEventsQuery(){ Events = new List<string>(){"a", "b"}};
```

or just...


```c#
client.MessageEvents.Find(new { Events = new []{"a", "b"}};
```

The trick is that the library uses conventions for converting the request based on the properties of the object, rather than the properties of a specific type.

**Comment by darrencauthon** [comment]
@asherber That's pretty much the approach I've taken with the entire library.  I found the ways that the SparkPost handles strings, numbers, arrays, etc., and then I mapped conventions to send the properties as I saw fit.

Another benefit to this approach is that it allows for people to extend or use the library in ways that I did not see when I started it.  For example, SparkPost has added properties to their API in the months since I wrote this library.  To support those new properties, I can update my library... but in the meantime, people can send the properties over by inheriting from my classes or writing their own anonymous types.

**Comment by asherber** [comment]
Okay, thanks. My personal inclination is to be more strict about these things and update the library as needed, but I'll follow your lead. I think I'm just about done with coding, unit tests, and some external testing as well. Will let you know soon.

**Comment by darrencauthon** [comment]
@asherber Thank you!  

I know what you mean, I used to be that way, too.... but I took a four-year hiatus from full-time C# in favor of Ruby. :smile:  It taught me the benefits of being looser with the typing in favor of the users of the library. :smile:

**Comment by asherber** [comment]
I think you could make a case for users' convenience either way. As a dev, I like strong  typing because it aids with discoverability and helps me avoid errors up front. If I pass an anonymous object into one of these functions, I might not see errors until the call actually hits the API, whereas a strongly typed object shows me what to do.

As a side note, I'm currently evaluating a few ESPs and writing some POC code for each. I immediately ruled out SendGrid because their official C# library makes extensive use of dynamics in its interfaces.

**Comment by darrencauthon** [comment]
Well, I can understand the discoverability with strong typing, which is why I created the query class.  

But restricting people into that specific type doesn't do much good, especially in a static language where our options to update and correct the library are very limited.  

> If I pass an anonymous object into one of these functions, I might not see errors until the call actually hits the API, whereas a strongly typed object shows me what to do.

The strong type does not fix this, as it's still possible not to call the library in a proper way that could cause unexpected results or errors.  Or even if the API is a perfect fit, it still might not work as one would expect.  As with any third-party vendor, it's best to trust them... but verify all the results.  Track what's sent, track what's returned, and watch it like a hawk.  I know strong typing helps with discoverability, to a point, but nothing beats documentation, working examples, and flexibility. :smile:

**Comment by asherber** [comment]
Okay, I think I'm going to call this done. There are unit tests in there for the basic stuff, and I've exercised all of the API calls as well. I'll submit the PR.

**Comment by darrencauthon** [comment]
Thank you! :smile: 👍

**Comment by darrencauthon** [comment]
@asherber got the work completed, and support is now available on Nuget!
