### ISSUE TITLE
Need compatibility with Json.NET 9

### ISSUE THREAD

**Issue by BogdanovKirill** [darrencauthon/csharp-sparkpost#118]
Hi,

After updating Json.NET to lastest version, I have exceptions like that:
One or more errors occurred. System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by darrencauthon** [comment]
Hmm... will take a look.

**Comment by darrencauthon** [comment]
@BogdanovKirill I took a look, and I was able to update Json without any trouble:

![screenshot_120116_055605_pm](https://cloud.githubusercontent.com/assets/148768/20817810/6f5788da-b7ef-11e6-8372-5554b82ae44e.jpg)

![screenshot_120116_055736_pm](https://cloud.githubusercontent.com/assets/148768/20817853/a5651384-b7ef-11e6-86f0-b119b7a0c399.jpg)

**Comment by darrencauthon** [comment]
@BogdanovKirill I will be happy to look at this problem further if you have more specifics.  It's very possible that I might be missing something, but it seems to be able to work against the latest Json 9.0.1 for me in a brand-new project.  

I'm going to close the ticket for now, just because I have nothing else to show.  If you can give me an example of the code or any additional information, and I'd be happy to reopen and investigate.

**Comment by darrencauthon** [comment]
For my own notes, in case this comes up again:

![screenshot_120116_060143_pm](https://cloud.githubusercontent.com/assets/148768/20817924/38d40224-b7f0-11e6-8735-35aefb9353eb.jpg)

**Comment by BogdanovKirill** [comment]
Thank you very much for your response! I will check again and give you more details
