### ISSUE TITLE
List of Template from Api

### ISSUE THREAD

**Issue by ManuelFunciona** [darrencauthon/csharp-sparkpost#37]
Hi people,

I'm migrating from mandrill to SparkPost

Does anyone know how to recover my templates from the Api in SparkPost?

In Mandrill there is a method called ListTemplates, but here I can not find anything.

Thank's!!!

**Comment by darrencauthon** [comment]
It's not in this library yet -- someone will have to code it.

Templates could be implemented similar to #35 .  

Do you need this via an API?  I thought Templates would probably be the **last** feature implemented in this library, as template management is handled very well through the SparkPost UI.

**Comment by ManuelFunciona** [comment]
Thanks for the reply

I have solved making a call cURL.

I have an email delivery system and is easier to load into a combo templates and send emails loading a excel.

The example of the call if someone needs

HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://api.sparkpost.com/api/v1/templates");
        request.Headers.Add("Authorization","MY_AUTHORIZATION");
        request.Accept = "application/json";
        using (var responseURL = (HttpWebResponse)request.GetResponse())
        {
            using (var reader = new StreamReader(responseURL.GetResponseStream()))
            {
                var objText = reader.ReadToEnd();
                var myObjResponse = JsonConvert.DeserializeObject(objText);
            }
        }

**Comment by jamesoflol** [comment]
Hey Darren

I just started writing in templates support. The "Create" feature is complete. I realised I should probably ask you before I finish/polish, to check that I'm on the right track - I don't generally work with Interfaces, and the datamapping code is pretty fancy, but I think I've got it right

If you could please check it out that'd be great. Thanks.

https://github.com/jamesoflol/csharp-sparkpost/tree/templates-support

**Comment by darrencauthon** [comment]
@jamesoflol I think yo uare definitely on the right track.

I created a PR from your code and this codebase for checking at https://github.com/SparkPost/csharp-sparkpost/pull/40/files.  I think you'll need to try another branch to get this feature added.  Are you working on OSX or Linux with Mono?  It seems that every file you touched was changed entirely, probably via end-of-line character change?  

For comparison, look at  https://github.com/SparkPost/csharp-sparkpost/pull/35/files.  I'm adding a similar feature, yet you only see the changes I've made.

Here is a line that might help on handling end-of-line with git. I love you addition and would love to accept the PR, but I can't merge such a drastic change to so many files.

 https://help.github.com/articles/dealing-with-line-endings/

**Comment by jamesoflol** [comment]
Hey Darren,

Thanks very much for the feedback.

I feel like a fair bozo for not checking the adds/deletes in Github. They looked fine in VS. I'm using VS 2015 on Win10. Turns out my VS was turning all line endings in to CRLF, and as you said, gratuitously doing it to every file I touched. All existing EOL seem to be LF.

I've made a new branch and copied the changes in, in order to prevent mucho pollution. All additions, no deletions. I've put in a .gitattributes file that forces LF.

#44 

I'm not quite sure why it says there are conflicts when there's only additions and no deletions?

**Comment by jamesoflol** [comment]
Oh and one other thing - There was a message saying there are conflicts, even though it's all additions and no deletes... Is this because your repo is 10 commits ahead of mine? Should I be pulling in your latest changes to my branch immediately before making a pull request back to you?

**Comment by darrencauthon** [comment]
Just git pull origin master into your branch... I bet the merge conflict is in the project file, just include all lines. 
Or if you want, I can resolve it on this side.... I'll just need to create a new branch before we merge. 
Get Outlook for iOS




On Thu, Apr 21, 2016 at 11:05 PM -0700, "jamesoflol" <notifications@github.com> wrote:












Oh and one other thing - There was a message saying there are conflicts, even though it's all additions and no deletes... Is this because your repo is 10 commits ahead of mine? Should I be pulling in your latest changes to my branch immediately before making a pull request back to you?

**Comment by jamesoflol** [comment]
Nah it's cool - ill merge and fix on monday. Thanks





On Fri, Apr 22, 2016 at 2:17 PM -0700, "Darren Cauthon" <notifications@github.com<mailto:notifications@github.com>> wrote:

Just git pull origin master into your branch... I bet the merge conflict is in the project file, just include all lines.
Or if you want, I can resolve it on this side.... I'll just need to create a new branch before we merge.
Get Outlook for iOS




On Thu, Apr 21, 2016 at 11:05 PM -0700, "jamesoflol" <notifications@github.com> wrote:












Oh and one other thing - There was a message saying there are conflicts, even though it's all additions and no deletes... Is this because your repo is 10 commits ahead of mine? Should I be pulling in your latest changes to my branch immediately before making a pull request back to you?



-
You are receiving this because you commented.
Reply to this email directly or view it on GitHub













-

**Comment by darrencauthon** [comment]
Why, I believe this is done! :smile:
